dappx/urls.py
# dappx/urls.py
from django.conf.urls import url
from dappx import views
from dprojx import settings
# SET THE NAMESPACE!
app_name = 'dappx'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^offerdetails/$',views.register,name='offerdetails'),
    ]

dprojx/urls.py
# dprojx/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from dappx import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^dappx/',include('dappx.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

dappx/models.py
# dappx/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

# Create your models here.
# class UserProfileInfo(models.Model):
#     user = models.OneToOneField(User,on_delete=models.CASCADE)
#     portfolio_site = models.URLField(blank=True)
#     profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
#     content = models.TextField(max_length=300)
# def __str__(self):
#   return self.user.username
class Person(models.Model):
    name = models.CharField(max_length=96)
    email= models.EmailField(max_length=254, blank=False, unique=True,
        error_messages={'required': 'Please provide your email address.',
                        'unique': 'An account with this email exist.'},)
    phone =  models.CharField(max_length=10)
    city = models.CharField(max_length=96)
    date_registered = models.TimeField
    query = models.TextField(max_length=300,default='I am interested. Please call on XXXXXXXXXX', editable=True)
    
# from django.forms import ModelForm

# class SubscribeForm(ModelForm):
#     class Meta:
#         model = Person
#         exclude = ('date_subscribed','messages_received')

dappx/forms.py
# dappx/forms.py
from django import forms
from dappx.models import Person
from django.contrib.auth.models import User

class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = Person
         fields = ('name','email','phone','city','query')
         required_css_class = 'bold'

dappx/views.py
# dappx/views.py
from django.shortcuts import render
from dappx.forms import UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage

def index(request):
    return render(request,'dappx/index.html')
@login_required
def special(request):
    return HttpResponse("You are logged in !")
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
def register(request):
    registered = False
    if request.method == 'POST':
        #user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if profile_form.is_valid():
#            user = user_form.save()
#            user.set_password(user.password)
 #           user.save()
            profile = profile_form.save(commit=False)
            customer_name=profile_form.cleaned_data['name']
            customer_phone=profile_form.cleaned_data['phone']
            email = EmailMessage('New Registration: '+customer_name, customer_name+' is interested in the tour package. Please call him on '+customer_phone+' to discuss further.', to=['prabhat4vedi@gmail.com'])
            email.send()
            print(customer_name,customer_phone)
            from twilio.rest import Client
            from django.conf import settings

            to = '+918169813384'
            client = Client(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)
            response = client.messages.create(body='New Registration: '+customer_name+'. '+customer_name+' is interested in the tour package. Please call him on '+customer_phone+' to discuss further.', 
                 to=to, from_=settings.TWILIO_PHONE_NUMBER)
  #S          profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(profile_form.errors)
    else:
        profile_form = UserProfileInfoForm()
    return render(request,'dappx/registration.html',
                          {'profile_form':profile_form,
                           'registered':registered})
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'dappx/login.html', {})

templates/dappx/Dreamtime Travels.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0037)http://127.0.0.1:8000/dappx/register/ -->
<html xmlns="https://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Dreamtime Travels</title>



  
    
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="./Dreamtime Travels_files/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

          <li><a class="navbar-brand" href="http://127.0.0.1:8000/">
        <img src="./Dreamtime Travels_files/Dreamtime-Travel-Logo.png" width="150" height="150">
</a></li>
          <li><a class="navbar-link" href="http://127.0.0.1:8000/admin/">Admin</a></li>
          <li><a class="navbar-link" href="http://127.0.0.1:8000/dappx/register/">Register</a></li>     
          
          
            <li><a href="http://127.0.0.1:8000/logout/">Logout</a></li>
          
</ul>
      </div>
    </nav>
    <div class="container">
    
  <div class="container">
    <div class="jumbotron">
      
     <table>
      <tbody><tr>
      </tr>
     </tbody></table> 
<form method="POST">
<style type="text/css">
			/* CSS Document */

		
@font-face{font-family:'Roboto';font-style:normal;font-weight:400;src:local('Roboto Regular'),local(Roboto-Regular),url(https://fonts.gstatic.com/s/roboto/v12/2UX7WLTfW3W8TclTUvlFyQ.woff) format("woff")}

 body{padding:0;margin:0;font-family:'Roboto',sans-serif,Arial,Verdana;background-color:#fff}			
			

h1
{
font-weight:normal;
font-size:30px;
color:lime;
padding:100px;
margin:100px;
}

h2
{
margin:0px;
padding:0px;
color:lime;
font-size:30px;
}

p
{
margin-left:8px;
padding:0;
margin-top:0px;
margin-bottom:0px;
color:aqua;
font-size:18px;
}

.input
{
width:92%;
border:10px solid #cccccc;
margin-left:115px;
border-radius:114px;
padding:115px;
height:1511px;
}


textarea
{
height:60px;
width:96%;
border:1px solid #cdeccc;
margin-left:5px;
border-radius:4px;
padding:5px;
box-sizing:border-box;
}

.style1 {color: #C27074}
.fl{float:left;}

.sbt
{
background-color:#de691a; color:#ffffff; border:3px solid #a24713; border-radius:10px; font-size:28px; padding:1px 10px; cursor:pointer;
}

	@media only screen and (max-width: 640px)  
            {
					.devi-wid {width:440px!important; padding:0;}	
					.cen {text-align: center!important;} 
			}
	@media only screen and (max-width: 479px) 
			{
					 .devi-wid {width:325px!important; padding:0;}	
					 .cen {text-align: center!important;}					 
			}
					<style>
thead {color:green;}
tbody {color:blue;}
tfoot {color:red;}

table, th, td {
  border: 0px solid black;
  
}
</style>

<table>
    <tbody><tr>
        <td>     
        <h2><div align="center" style="background-color:green; color:aqua; font-size:20px;padding:8px 10px;">Registration Details</div>
    </h2></td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>

        <td width="50" height="50" align="right"><img src="./Dreamtime Travels_files/Dreamtime-Travel-Logo.png" width="150" height="150"></td>
</tr>

</tbody></table>
          <table border="1">
          <input type="hidden" name="csrfmiddlewaretoken" value="JfAHEmjd6aGGP8JHAkDBMlY8qskGIexdCNswG3n91cxn106akKqqhT0zevJ65YtN">
 <tbody><tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td>
          </td></tr><tr><th><label for="id_name">Name:</label></th><td><input type="text" name="name" maxlength="96" required="" id="id_name"></td></tr>
<tr><th><label for="id_email">Email:</label></th><td><input type="email" name="email" maxlength="254" required="" id="id_email"></td></tr>
<tr><th><label for="id_phone">Phone:</label></th><td><input type="text" name="phone" maxlength="10" required="" id="id_phone"></td></tr>
<tr><th><label for="id_city">City:</label></th><td><input type="text" name="city" maxlength="96" required="" id="id_city"></td></tr>
<tr><th><label for="id_content">Content:</label></th><td><textarea name="content" cols="40" rows="10" maxlength="300" required="" id="id_content"></textarea></td></tr>

<tr><td></td>
</tr>
          <tr><th align="center">
          <input name="btn_submit" type="submit" value="Register" onclick="return valid_signup();" class="sbt">

          </th></tr>

          </tbody></table>
</form>
      
    </div>
  </div>


    </div>
  
</body></html>

templates/dappx/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><img border="0" alt="W3Schools" src="http://www.gtoad.com/wp-content/uploads/2017/09/Dreamtime-Travel-Logo.png" width="100" height="100"><a class="navbar-brand" href="{% url 'index' %}"></a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'dappx:register' %}">Register</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'dappx:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/dappx/index.html
{% extends "dappx/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to Dreamtime Travels</h1>
    {% if user.is_authenticated %}
        <h2>Hello Mr. {{ user.username }} ,How are you today?</h2>
    {% else %}
        <h2>Register if you are looking for best travel packages    </h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/dappx/index1.html
<!DOCTYPE html>
<!-- saved from url=(0122)file:///C:/Users/Admin/Downloads/RS%20HTML%20107%20Free%20Website%20Template%20-%20Free-CSS.com/ATN-RSH-000107/index.html# -->
<html class="js cssanimations flexbox canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers applicationcache svg inlinesvg smil svgclippaths translated-ltr" style=""><!--<![endif]--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
       
        <link rel="stylesheet" href="file:///C:/Users/Admin/Downloads/RS%20HTML%20107%20Free%20Website%20Template%20-%20Free-CSS.com/ATN-RSH-000107/css/bootstrap.css">
        <link rel="stylesheet" href="file:///C:/Users/Admin/Downloads/RS%20HTML%20107%20Free%20Website%20Template%20-%20Free-CSS.com/ATN-RSH-000107/css/bootstrap-responsive.css">
        <link rel="stylesheet" href="file:///C:/Users/Admin/Downloads/RS%20HTML%20107%20Free%20Website%20Template%20-%20Free-CSS.com/ATN-RSH-000107/css/custom-styles.css">
        <link rel="stylesheet" href="file:///C:/Users/Admin/Downloads/RS%20HTML%20107%20Free%20Website%20Template%20-%20Free-CSS.com/ATN-RSH-000107/css/font-awesome.css">
        <link rel="stylesheet" href="file:///C:/Users/Admin/Downloads/RS%20HTML%20107%20Free%20Website%20Template%20-%20Free-CSS.com/ATN-RSH-000107/css/component.css">
        <link rel="stylesheet" href="file:///C:/Users/Admin/Downloads/RS%20HTML%20107%20Free%20Website%20Template%20-%20Free-CSS.com/ATN-RSH-000107/css/font-awesome-ie7.css">
 
        <script src="file:///C:/Users/Admin/Downloads/RS%20HTML%20107%20Free%20Website%20Template%20-%20Free-CSS.com/ATN-RSH-000107/js/modernizr.custom.js"></script>
        <script src="file:///C:/Users/Admin/Downloads/RS%20HTML%20107%20Free%20Website%20Template%20-%20Free-CSS.com/ATN-RSH-000107/js/modernizr-2.6.2-respond-1.1.0.min.js"></script>
    <link type="text/css" rel="stylesheet" charset="UTF-8" href="./index1_files/translateelement.css"></head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->

        <!-- This code is taken from http://twitter.github.com/bootstrap/examples/hero.html -->
        
        <div class="wrapper-blue">
            <div class="site-header">
                <div class="logo">
                    <h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Paree </font></font><span><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Tours and Travels</font></font></span></h1>
                </div>
                <div class="menu-bar">
                    <div class="navbar">
                                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                                    <i class="fw-icon-th-list"></i>
                                </a>
                                <div class="nav-collapse collapse in" style="height: 0px;">
                                    <ul class="nav">
                                        <li class="active"><a href="file:///C:/Users/Admin/Downloads/RS%20HTML%20107%20Free%20Website%20Template%20-%20Free-CSS.com/ATN-RSH-000107/index.html#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">home</font></font></a></li>
                                        <li><a href="file:///C:/Users/Admin/Downloads/RS%20HTML%20107%20Free%20Website%20Template%20-%20Free-CSS.com/ATN-RSH-000107/index.html#about"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">About</font></font></a></li>
                                        <li><a href="file:///C:/Users/Admin/Downloads/RS%20HTML%20107%20Free%20Website%20Template%20-%20Free-CSS.com/ATN-RSH-000107/index.html#services"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Services</font></font></a></li>
                                        <li><a href="file:///C:/Users/Admin/Downloads/RS%20HTML%20107%20Free%20Website%20Template%20-%20Free-CSS.com/ATN-RSH-000107/index.html#work"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">work</font></font></a></li>
                                        <li><a href="file:///C:/Users/Admin/Downloads/RS%20HTML%20107%20Free%20Website%20Template%20-%20Free-CSS.com/ATN-RSH-000107/index.html#contact"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Contact</font></font></a></li>
                                    </ul>
                                </div><!--/.nav-collapse -->
                        </div>
                    </div>
                <div class="container">
                    <div class="ruler"></div>
                </div>
                <div class="container">
                <div class="menu">
                    <div class="navbar">
                                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                                    <i class="fw-icon-th-list"></i><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> NAVIGATION
                                </font></font></a>
                                <div class="nav-collapse in collapse" style="height: auto;">
                                    <ul class="nav">
                                        <li class="active"><a href="file:///C:/Users/Admin/Downloads/RS%20HTML%20107%20Free%20Website%20Template%20-%20Free-CSS.com/ATN-RSH-000107/index.html#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">home</font></font></a></li>
                                        <li><a href="file:///C:/Users/Admin/Downloads/RS%20HTML%20107%20Free%20Website%20Template%20-%20Free-CSS.com/ATN-RSH-000107/index.html#about"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">About</font></font></a></li>
                                        <li><a href="file:///C:/Users/Admin/Downloads/RS%20HTML%20107%20Free%20Website%20Template%20-%20Free-CSS.com/ATN-RSH-000107/index.html#services"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Services</font></font></a></li>
                                        <li><a href="file:///C:/Users/Admin/Downloads/RS%20HTML%20107%20Free%20Website%20Template%20-%20Free-CSS.com/ATN-RSH-000107/index.html#work"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">work</font></font></a></li>
                                        <li><a href="file:///C:/Users/Admin/Downloads/RS%20HTML%20107%20Free%20Website%20Template%20-%20Free-CSS.com/ATN-RSH-000107/index.html#contact"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Contact</font></font></a></li>
                                    </ul>
                                </div><!--/.nav-collapse -->
                        </div>
                    </div>
                    </div>
                    <div class="container">
                        <div class="banner">
                            <div id="myCarousel" class="carousel slide">
                
                                <div class="carousel-inner">
                                  <div class="item">
                                    <img src="file:///C:/Users/Admin/Downloads/RS%20HTML%20107%20Free%20Website%20Template%20-%20Free-CSS.com/ATN-RSH-000107/img/banner-image.png" alt="">
                                    <div class="carousel-caption">
                                      <h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">tirmiopsumdo</font></font></h1><br>
                                      <h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Augun pleasure koising</font></font></h2>
                                    </div>
                                  </div>
                                  <div class="item active left">
                                    <img src="file:///C:/Users/Admin/Downloads/RS%20HTML%20107%20Free%20Website%20Template%20-%20Free-CSS.com/ATN-RSH-000107/img/banner-image.png" alt="">
                                    <div class="carousel-caption">
                                      <h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">tirmiopsumdo</font></font></h1><br>
                                      <h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Augun pleasure koising</font></font></h2>
                                    </div>
                                  </div>
                                  <div class="item next left">
                                    <img src="file:///C:/Users/Admin/Downloads/RS%20HTML%20107%20Free%20Website%20Template%20-%20Free-CSS.com/ATN-RSH-000107/img/banner-image.png" alt="">
                                    <div class="carousel-caption">
                                      <h1><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">tirmiopsumdo</font></font></h1><br>
                                      <h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Augun pleasure koising</font></font></h2>
                                    </div>
                                  </div>

                                </div>
                                <ol class="carousel-indicators">
                                  <li data-target="#myCarousel" data-slide-to="0" class=""></li>
                                  <li data-target="#myCarousel" data-slide-to="1" class=""></li>
                                  <li data-target="#myCarousel" data-slide-to="2" class=""></li>
                                </ol>
                            </div>
              
                        </div>
                    </div>
                </div>
            </div>
            
   
                
                
                
                
            

        

         

        


    
    
    
    
    



    

</body></html>

templates/dappx/login.html
{% extends 'dappx/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'dappx:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

templates/dappx/offerdetails.html
	  <table width="450" border="0" align="left" cellpadding="0" cellspacing="0" class="devi-wid">
          <tr>
	  <td valign="top" height="450">
		<div style="margin:25px 20px 20px; font-size:16px; color:silver;  border:1px solid #888; ">
		<div style="background-color:green; color:aqua; font-size:20px;padding:8px 10px;">Offer Details</div>
			        >>> Welcome drink on arrival.<br/>
		<div style="padding:8px; line-height:30px;">
		>>> Valid for 3 Days + 2 Nights.<br/>
		>>> Valid for 2 Adults & 2 Kids(Upto 5 years).<br/>
		>>> 25 Listed Destinations in India & 9 Overseas.<br/>
		>>> Pickup & Drop Facility Available.<br/>  
		>>> 2 Breakfasts + 2 Dinners.<br/>
		>>> Package valid for 7 months only.<br/>
		>>> Get 7000 Redemption Points & can be Redeemed on Kandeal Portal.<br/>
		>>> Minimum 60 days advance booking from the date of travel.<br/>		
				</div>
		</div>
		</td>
	  </tr>
      </table>  